language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t pjoisha/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pjoisha/react-test npm test

after_success:
  - docker build -t pjoisha/multi-client ./client
  - docker build -t pjoisha/multi-nginx ./nginx
  - docker build -t pjoisha/multi-server ./server
  - docker build -t pjoisha/multi-worker ./worker
  # Log in to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and psuh them to docker hub
  - docker push pjoisha/multi-client
  - docker push pjoisha/multi-nginx
  - docker push pjoisha/multi-server
  - docker push pjoisha/multi-worker

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
